title: Newton Framework Documentation
description: >
    Newton is a full-stack web framework written in C++ allowing you to
    write server applications in C++ and the NCL front-end language.
lang: en-US

git_address: https://github.com/hakonmagnus/newton

bootwatch: paper

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-redirecct-from
    - jekyll-seo-tag
    - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - README.md
    - vendor

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      sectionid: blog

  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      sectionid: docs
      seo:
        type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
